all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    kubernetes_version: "1.28"
    
  children:
    k8s_cluster:
      hosts:
        master-01:
          ansible_host: 192.168.1.10
        worker-01:
          ansible_host: 192.168.1.11
        worker-02:
          ansible_host: 192.168.1.12