apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdd-navigator.fullname" . }}-config
  labels:
    {{- include "sdd-navigator.labels" . | nindent 4 }}
data:
  API_HOST: "0.0.0.0"
  API_PORT: "8080"
  RUST_LOG: {{ .Values.api.env | dig "RUST_LOG" "info" }}
  {{- if .Values.frontend.enabled }}
  NEXT_PUBLIC_API_URL: {{ .Values.frontend.env | dig "NEXT_PUBLIC_API_URL" "" | quote }}
  {{- end }}