apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdd-navigator.fullname" . }}-secrets
  labels:
    {{- include "sdd-navigator.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ printf "postgres://%s:%s@%s-postgresql:%d/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "sdd-navigator.fullname" .) 5432 .Values.postgresql.auth.database | b64enc | quote }}
  {{- if .Values.redis.enabled }}
  redis-url: {{ printf "redis://:%s@%s-redis-master:%d" .Values.redis.auth.password (include "sdd-navigator.fullname" .) 6379 | b64enc | quote }}
  {{- end }}